"""create saved scenarios

Revision ID: 20260923_01
Revises:
Create Date: 2026-09-23 12:02:16.914157+00:00
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = '20260923_01'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'scenarios',
        sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
        sa.Column('name', sa.Text(), nullable=False),
        sa.Column('decisions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('dataset_version', sa.Text(), nullable=False),
        sa.Column('dataset_hash', sa.Text(), nullable=False),
        sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('score', sa.Float(), nullable=False),
        sa.Column('spent', sa.Integer(), nullable=False),
        sa.Column('budget', sa.Integer(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('ix_scenarios_created_at', 'scenarios', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
